config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', 
    path_names: { sign_in: 'login', sign_out: 'logout'},
    controllers: {
      sessions: 'users/sessions'
    }

  root to: redirect('comments')
  get 'comments', to: 'comments#index'
  authenticated :user do
    mount RailsDb::Engine => '/rails/db', :as => 'rails_db'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :yt_comment_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all

    if (params.has_key?(:q))
      @comments = @comments.where("lower(text_display) LIKE ?", "%#{params[:q].gsub("'", "&#39;").downcase}%")
    end
    
    if (params.has_key?(:exclude_of_course) && params[:exclude_of_course] == "on")
      @comments = @comments.where("lower(text_display) ~* ?", '(?<![oO][fF]\s)(course)')
    end

    if !params.has_key?(:after) || params[:after] == ""
      params[:after] = "01/01/1900".to_date
    end

    if !params.has_key?(:before) || params[:before] == ""
      params[:before] = Date.today
    end

    @comments = @comments.where(comment_published_at: params[:after].to_datetime.beginning_of_day..params[:before].to_datetime.end_of_day)


    if !params.has_key?(:results_per_page) || params[:results_per_page] == ""
      params[:results_per_page] = 50
    end
    
    if (params.has_key?(:sort_by) && params[:sort_by] == "Date: New - Old")
      @comments = @comments.order(comment_published_at: :desc)
    else
      @comments = @comments.order(comment_published_at: :asc)
    end
    
    @comments = @comments.paginate(page: params[:page], per_page: params[:results_per_page])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<div class="p-4">
  <%= form_with(url: "comments", method: "get", local: true) do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q, params[:q]) %>
    <%= label_tag(:after, "After Date:") %>
    <%= date_field_tag(:after, params[:after]) %>
    <%= label_tag(:before, "Before Date:") %>
    <%= date_field_tag(:before, params[:before]) %>
    <span style="background-color:#999999;">
        <%= label_tag(:exclude_of_course, "Exclude 'of course' unless also just 'course':") %>
        <%= check_box_tag(:exclude_of_course, params[:exclude_of_course], params[:exclude_of_course]) %>
    </span>
    <%= label_tag(:sort_by, "Sort By:") %>
    <%= select_tag(:sort_by, options_for_select(["Date: Old - New", "Date: New - Old"], params[:sort_by])) %>
    <%= label_tag(:results_per_page, "Results Per Page:") %>
    <%= select_tag "results_per_page", options_for_select([10,50,100,500,1000], params[:results_per_page]) %>
    <%= submit_tag("Search") %>
  <% end %>
</div>
<%= will_paginate @comments %>
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Text</th>
      <th scope="col">Username</th>
      <th scope="col">Date</th>
      <th scope="col">YT Link</th>
      <th scope="col">Likes</th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <th scope="row"><img src="<%= comment.author_profile_image_url %>"></th>
        <td> <%= comment.text_display.html_safe %> </td>
        <td><a href="<%= comment.author_channel_url %>"><%= comment.author_display_name.html_safe %></a></td>
        <td> <%= comment.comment_published_at.strftime("%F") %> </td>
        <td> <a href="https://www.youtube.com/watch?v=<%= comment.video_id %>&lc=<%= comment.yt_comment_id %>">Comment</a> </td>
        <td> 👍<%= comment.like_count %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubeCommentSearcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light px-4">
      <a class="navbar-brand" href="<%= comments_path %>" style="font-color: red;">Youtube Comment Searcher</a>
      <% if user_signed_in? %>
       <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
      <% end %>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>